# Generated by Django 5.2.1 on 2025-05-28 21:57

import datetime
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[store.validators.validate_age_18], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=datetime.date(2025, 5, 29), max_length=30, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[store.validators.validate_age_18], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
